language: php
jobs:
  fast_finish: true
  include:
    - php: 7.4
      env: COVERAGE=1
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly
branches:
  except:
    - /^dist/
    - /^release/
before_script:
  - ./scripts/travis/setup.sh
  - php -i
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - ./scripts/travis/uploadCodeCoverage.sh