site_name: s9e\TextFormatter
theme: readthedocs
extra_css: ["extra.css"]
repo_url: https://github.com/s9e/TextFormatter/
markdown_extensions:
  - sane_lists
nav:
  - Home: index.md
  - Getting started:
    - Installation: Getting_started/Installation.md
    - How it works: Getting_started/How_it_works.md
    - Using predefined bundles: Getting_started/Using_predefined_bundles.md
    - Runtime configuration: Getting_started/Runtime_configuration.md
    - Unparsing: Getting_started/Unparsing.md
  - Bundles:
    - Fatdown: Bundles/Fatdown.md
    - Forum: Bundles/Forum.md
    - MediaPack: Bundles/MediaPack.md
    - Your own bundle: Bundles/Your_own_bundle.md
  - Templating:
    - Introduction: Templating/Introduction.md
    - Modify a template: Templating/Modify_a_template.md
    - Template parameters: Templating/Template_parameters.md
    - Template security: Templating/Template_security.md
    - Template normalization:
      - Change the default settings: Templating/Template_normalization/Change_default.md
      - Extend the template syntax through normalization: Templating/Template_normalization/Extend.md
      - Examples: Templating/Template_normalization/Examples.md
  - Rules:
    - Tag rules: Rules/Tag_rules.md
    - Automatic rules generation: Rules/Automatic_rules_generation.md
    - Rules generators: Rules/Rules_generators.md
  - Filters:
    - Built-in filters: Filters/Built-in_filters.md
    - Add/replace filters: Filters/Custom_filters.md
    - Attribute filters: Filters/Attribute_filters.md
    - Tag filters: Filters/Tag_filters.md
    - Callback signature: Filters/Callback_signature.md
    - URL features:
      - Blacklist hosts: Filters/URL_features/Blacklist_hosts.md
      - Whitelist hosts: Filters/URL_features/Whitelist_hosts.md
      - Restrict schemes: Filters/URL_features/Schemes.md
  - Plugins:
    - Autoemail:
      - Synopsis: Plugins/Autoemail/Synopsis.md
    - Autoimage:
      - Synopsis: Plugins/Autoimage/Synopsis.md
    - Autolink:
      - Synopsis: Plugins/Autolink/Synopsis.md
    - Autovideo:
      - Synopsis: Plugins/Autovideo/Synopsis.md
    - BBCodes:
      - Synopsis: Plugins/BBCodes/Synopsis.md
      - Add from the repository: Plugins/BBCodes/Add_from_the_repository.md
      - Add custom BBCodes: Plugins/BBCodes/Add_custom_BBCodes.md
      - Custom BBCode syntax: Plugins/BBCodes/Custom_BBCode_syntax.md
      - Localize strings: Plugins/BBCodes/Localize_strings.md
      - Use template parameters: Plugins/BBCodes/Use_template_parameters.md
      - Add unsafe BBCodes: Plugins/BBCodes/Add_unsafe_BBCodes.md
    - Censor:
      - Synopsis: Plugins/Censor/Synopsis.md
      - Whitelist: Plugins/Censor/Whitelist.md
      - As a standalone: Plugins/Censor/Standalone.md
    - Emoji:
      - Synopsis: Plugins/Emoji/Synopsis.md
      - Configuration: Plugins/Emoji/Configuration.md
    - Emoticons:
      - Synopsis: Plugins/Emoticons/Synopsis.md
      - Add emoticons: Plugins/Emoticons/Add_emoticons.md
      - Toggle rendering: Plugins/Emoticons/Toggle_rendering.md
      - Change the matching regexp: Plugins/Emoticons/Change_regexp.md
    - Escaper:
      - Synopsis: Plugins/Escaper/Synopsis.md
    - FancyPants:
      - Synopsis: Plugins/FancyPants/Synopsis.md
    - HTMLComments:
      - Synopsis: Plugins/HTMLComments/Synopsis.md
    - HTMLElements:
      - Synopsis: Plugins/HTMLElements/Synopsis.md
      - Alias HTML elements to other tags: Plugins/HTMLElements/Aliases.md
    - HTMLEntities:
      - Synopsis: Plugins/HTMLEntities/Synopsis.md
    - Keywords:
      - Synopsis: Plugins/Keywords/Synopsis.md
      - Map keywords to IDs: Plugins/Keywords/Map.md
      - Automatically link MTG cards: Plugins/Keywords/MTG.md
    - Litedown:
      - Synopsis: Plugins/Litedown/Synopsis.md
      - Syntax: Plugins/Litedown/Syntax.md
    - MediaEmbed:
      - Synopsis: Plugins/MediaEmbed/Synopsis.md
      - Using default sites: Plugins/MediaEmbed/Using_default_sites.md
      - Supported sites: Plugins/MediaEmbed/Sites.md
      - Add a custom site: Plugins/MediaEmbed/Add_custom.md
      - Add a link to the original URL: Plugins/MediaEmbed/Append_template.md
      - Change a template: Plugins/MediaEmbed/Change_template.md
      - Configure a cache dir: Plugins/MediaEmbed/Performance_cache_dir.md
      - Support other markup: Plugins/MediaEmbed/Other_markup.md
    - PipeTables:
      - Synopsis: Plugins/PipeTables/Synopsis.md
      - Syntax: Plugins/PipeTables/Syntax.md
    - Preg:
      - Synopsis: Plugins/Preg/Synopsis.md
      - Practical examples: Plugins/Preg/Practical_examples.md
    - TaskLists:
      - Synopsis: Plugins/TaskLists/Synopsis.md
    - Your own plugin:
      - Plug your own parser: Plugins/Your_own_plugin/Register_parser.md
      - Create tags: Plugins/Your_own_plugin/Create_tags.md
  - JavaScript:
    - Introduction: JavaScript/Introduction.md
    - Live preview attributes: JavaScript/Live_preview_attributes.md
    - Minifiers: JavaScript/Minifiers.md
  - Internals:
    - API docs: Internals/API_docs.md
    - API changes: Internals/API_changes.md
    - General changes: Internals/Changes.md
    - Limits: Internals/Limits.md
    - PHP renderer: Internals/PHP_renderer.md
    - Storage format: Internals/Storage_format.md
    - Tag priorities: Internals/Tag_priorities.md
